### PR TITLE
Import the container image if any tag is not found on the current ones.

### PR DESCRIPTION
**Pull request by ereslibre**
This will ensure that as long as there's one unmatched new tag, we'll
import (and retag) the container image.

Fixes: bsc#1090841

### CODE REVIEW

**Comment by ereslibre** [comment]
Will verify the fix and give feedback here.

**Comment by vrothberg** [comment]
@ereslibre Did you verify it's working?

**Comment by ereslibre** [comment]
I can confirm it works in an artificial test I did, but didn't yet verify it works in the original environment where this happened:

```
caasp-admin:~ # docker images | grep haproxy
sles12/haproxy            1.6.0               ae179d271f06        17 hours ago        172MB
sles12/haproxy            1.6.0-1.271         ae179d271f06        17 hours ago        172MB
sles12/haproxy            latest              ae179d271f06        17 hours ago        172MB
caasp-admin:~ # docker rmi sles12/haproxy:1.6.0-1.271
Untagged: sles12/haproxy:1.6.0-1.271
caasp-admin:~ # container-feeder
caasp-admin:~ # docker images | grep haproxy
sles12/haproxy            1.6.0               ae179d271f06        17 hours ago        172MB
sles12/haproxy            latest              ae179d271f06        17 hours ago        172MB
caasp-admin:~ # ./container-feeder 
INFO[0003] Successfully imported the following images:  
INFO[0003]   - docker.io/sles12/haproxy:1.6.0           
caasp-admin:~ # docker images | grep haproxy
sles12/haproxy            1.6.0               ae179d271f06        17 hours ago        172MB
sles12/haproxy            1.6.0-1.271         ae179d271f06        17 hours ago        172MB
sles12/haproxy            latest              ae179d271f06        17 hours ago        172MB
```

**Comment by ereslibre** [comment]
I confirm this fix works on the affected original environment.

**Comment by ereslibre** [comment]
[Bug 1090841 - updates can break when container-feeder skips loading images](https://trello.com/c/Y8L2WZCx/823-bug-1090841-updates-can-break-when-container-feeder-skips-loading-images)

**Pull request merged**
