### PR TITLE
circumvent rpm bin for travis builds

### PR DESCRIPTION
**Pull request by PI-Victor**
ignore this PR for now, just testing some stuff out.

### CODE REVIEW

**Comment by flavio** [comment]
This is not enough. I propose to simply skip the test it there's no rpm binary available.

This is a temp project after all

**Comment by PI-Victor** [comment]
you're right, i was only mucking about, it's fixed now. PTAL!

ofc ubuntu install rpm in `/usr/bin/rpm` and opensuse in `/bin/rpm`. lol. booo!

**Comment by PI-Victor** [comment]
@flavio do you want to merge this?

**Comment by flavio** [comment]
Yes, my review request was stuck... 🤦‍♂️

**Comment by PI-Victor** [comment]
no worries! issue is addressed now.

**Comment by PI-Victor** [comment]
ah, i forgot to rebase. well that's that i guess

**Pull request merged**
