### PR TITLE
Add tests for NewFeeder module

### PR DESCRIPTION
**Pull request by mjura**

### CODE REVIEW

**Comment by flavio** [comment]
I'm don't like this code. It requires to have docker running on the test system and it requires to add a test image to the repo.

I would change the test to mock the interactions with docker. Something similar to what we did with `zypper-docker`. You can ask @mssola more about that if you need.

**Comment by mjura** [comment]
Hi, during working on mockup functions I have found go lang bug:
```
		have ImageImport("github.com/docker/docker/vendor/golang.org/x/net/context".Context, types.ImageImportSource, string, types.ImageImportOptions) (io.ReadCloser, error)
		want ImageImport("golang.org/x/net/context".Context, types.ImageImportSource, string, types.ImageImportOptions) (io.ReadCloser, error)
```
I tried to fix it with tips from https://github.com/golang/oauth2/issues/178#issuecomment-260294124 but it didn't help

**Comment by mjura** [comment]
My proposal would be to accept this test, since this test https://github.com/kubic-project/container-feeder/blob/master/docker_test.go#L8  also require to have `docker installed`

**Comment by flavio** [comment]
I'm closing the issue as discussed on mumble. We are going to kill this project as soon as our public registry is ready.

We should not spend too much time on this task (given all the weird go issues).

**Pull request closed without merging**
